package model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;
import lombok.ToString;

@Data
@ToString
@DynamoDBTable(tableName = "mysqsmsgtable")
public class MySqsMsgTable {

    @DynamoDBHashKey(attributeName = "msgid")
    @DynamoDBAutoGeneratedKey
    private String msgId;
    @DynamoDBRangeKey
    private String msg;
}
